name: "Lint"

on:
  push:
    branches:
      - "**"
      - "!release"
    tags:
      - "*"
  pull_request:

env:
  SET_GH_OUTPUT: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Check formatting"
        run: ./fbt lint_all
